language: cpp
sudo: false
dist: trusty
cache: bundler

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - cmake
        - clang-5.0
        - libc++-dev
        - libc++abi-dev
    env:
    - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get install -y libnotify-dev
- sudo apt-get install -y libglib2.0-dev

branches:
  only:
  - cpp

script:
# Check versions of gcc, g++ and cmake
- gcc -v && g++ -v && cmake --version
- mkdir -p build
- cd build
- showinfo "Configuring CMake"
- cmake -DCMAKE_BUILD_TYPE=Debug ..
- showinfo "Compiling"
- make

env:
  global:
  - LANG="en_US.UTF-8"
