language: cpp
sudo: false
dist: trusty
cache: bundler

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-6.0
        packages:
        - cmake
        - clang-6.0
        - libc++-dev
        - libc++abi-dev
        - libstdc++-6-dev
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get install -y libnotify-dev
- sudo apt-get install -y libglib2.0-dev

branches:
  only:
  - cpp

script:
- mkdir -p build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make

env:
  global:
  - LANG="en_US.UTF-8"
