language: cpp
sudo: false
dist: trusty
cache: bundler

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
    env:
    - COMPILER=g++-6 CC=gcc-6 CXX=g++-6 TARGETS="compiler-gcc"
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
        - libc++-dev
        - libc++abi-dev
    env:
    - COMPILER=clang++-4.0 CC=clang-4.0 CXX=clang++-4.0

before_install:
- sudo apt-get install -y libnotify-dev
- sudo apt-get install -y libglib2.0-dev

branches:
  only:
  - cpp

script:
# Check versions of gcc, g++ and cmake
- gcc -v && g++ -v && cmake --version
- mkdir -p build
- cd build
- showinfo "Configuring CMake"
- cmake -DCMAKE_BUILD_TYPE=Debug ..
- showinfo "Compiling"
- make

env:
  global:
  - LANG="en_US.UTF-8"
